package controller;

import exception.AppException;
import model.LostReport;
import service.LostReportService;
import service.impl.LostReportServiceImpl;
import util.UiStyle;
import util.IconFactory;
import javax.swing.*;import javax.swing.table.DefaultTableModel;import java.awt.*;

public class LostReportFrame extends JFrame {
    private JTextField txtId, txtPetId, txtDate, txtLocation, txtPhone; private JComboBox<String> comboStatus; private JTextArea txtDesc; private JTable table; private DefaultTableModel model; private final LostReportService service=new LostReportServiceImpl();
    public LostReportFrame(){ initialize(); loadData(); }
    private void initialize(){ setTitle("PetLife - 走失協尋通報 CRUD"); setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); setSize(1080,680); setLocationRelativeTo(null); JPanel root=new JPanel(null); root.setBackground(UiStyle.BG); setContentPane(root); JLabel title=UiStyle.title("走失協尋通報"); title.setBounds(32,24,260,38); root.add(title); JButton back=UiStyle.secondaryButton("返回首頁"); back.setIcon(IconFactory.icon(IconFactory.Type.BACK,16,UiStyle.PRIMARY_DARK)); back.setBounds(900,28,120,34); root.add(back); back.addActionListener(e->{new HomeFrame().setVisible(true);dispose();}); JPanel form=new UiStyle.RoundedPanel(28, Color.WHITE); form.setBounds(30,85,360,520); root.add(form); JLabel ft=new JLabel("通報資料"); ft.setFont(UiStyle.font(Font.BOLD,20)); ft.setBounds(24,20,180,30); form.add(ft); txtId=input(form,"ID",70,true); txtPetId=input(form,"寵物ID *",115,false); txtDate=input(form,"走失日期",160,false); txtLocation=input(form,"走失地點",205,false); txtPhone=input(form,"聯絡電話",250,false); comboStatus=combo(form,"狀態",new String[]{"協尋中","已找回","已結案"},295); JLabel nl=new JLabel("特徵描述"); nl.setFont(UiStyle.font(Font.PLAIN,14)); nl.setBounds(24,340,90,24); form.add(nl); txtDesc=new JTextArea(); txtDesc.setLineWrap(true); txtDesc.setFont(UiStyle.font(Font.PLAIN,14)); JScrollPane d=new JScrollPane(txtDesc); d.setBounds(125,340,197,120); form.add(d); addButtons(root); model=new DefaultTableModel(new Object[]{"ID","寵物ID","寵物名","日期","地點","電話","狀態","描述"},0){public boolean isCellEditable(int r,int c){return false;}}; table=new JTable(model); table.setRowHeight(28); table.setFont(UiStyle.font(Font.PLAIN,13)); table.getTableHeader().setFont(UiStyle.font(Font.BOLD,13)); UiStyle.styleTable(table); JScrollPane sp=new JScrollPane(table); sp.setBounds(415,160,610,445); root.add(sp); table.getSelectionModel().addListSelectionListener(e->{if(!e.getValueIsAdjusting())fill();}); }
    private void addButtons(JPanel root){ JPanel p=new JPanel(null); p.setBackground(UiStyle.BG); p.setBounds(415,85,610,62); root.add(p); String[] n={"新增","修改","刪除","清除","重新整理"}; for(int i=0;i<n.length;i++){ JButton b=i==0?UiStyle.primaryButton(n[i]):UiStyle.secondaryButton(n[i]); if(i==0)b.setIcon(IconFactory.icon(IconFactory.Type.ADD,16,Color.WHITE)); else if(i==1)b.setIcon(IconFactory.icon(IconFactory.Type.EDIT,16,UiStyle.PRIMARY_DARK)); else if(i==2)b.setIcon(IconFactory.icon(IconFactory.Type.DELETE,16,UiStyle.PRIMARY_DARK)); else if(i==4)b.setIcon(IconFactory.icon(IconFactory.Type.REFRESH,16,UiStyle.PRIMARY_DARK)); b.setBounds(i*105,10,i==4?120:90,38); p.add(b); final int k=i; b.addActionListener(e->{if(k==0)add();else if(k==1)update();else if(k==2)delete();else if(k==3)clear();else loadData();});}}
    private JTextField input(JPanel p,String t,int y,boolean ro){ JLabel l=new JLabel(t); l.setFont(UiStyle.font(Font.PLAIN,14)); l.setBounds(24,y,95,28); p.add(l); JTextField f=new JTextField(); f.setFont(UiStyle.font(Font.PLAIN,14)); f.setEditable(!ro); f.setBounds(125,y,197,32); UiStyle.styleField(f); p.add(f); return f;} private JComboBox<String> combo(JPanel p,String t,String[] items,int y){ JLabel l=new JLabel(t); l.setFont(UiStyle.font(Font.PLAIN,14)); l.setBounds(24,y,95,28); p.add(l); JComboBox<String> c=new JComboBox<>(items); c.setFont(UiStyle.font(Font.PLAIN,14)); c.setBounds(125,y,197,30); p.add(c); return c;}
    private LostReport read(boolean needId){ return new LostReport(needId?num(txtId.getText(),"請先選擇資料"):0,num(txtPetId.getText(),"寵物ID請輸入整數"),"",txtDate.getText().trim(),txtLocation.getText().trim(),txtPhone.getText().trim(),comboStatus.getSelectedItem().toString(),txtDesc.getText().trim());}
    private void add(){try{service.add(read(false));ok("新增成功");clear();loadData();}catch(Exception e){err(e);}} private void update(){try{service.update(read(true));ok("修改成功");clear();loadData();}catch(Exception e){err(e);}} private void delete(){try{int id=num(txtId.getText(),"請先選擇資料");if(JOptionPane.showConfirmDialog(this,"確定刪除？","確認",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){service.delete(id);clear();loadData();}}catch(Exception e){err(e);}}
    private void loadData(){try{model.setRowCount(0);for(LostReport r:service.getAll())model.addRow(new Object[]{r.getId(),r.getPetId(),r.getPetName(),r.getLostDate(),r.getLostLocation(),r.getContactPhone(),r.getStatus(),r.getDescription()});}catch(Exception e){err(e);}} private void fill(){int r=table.getSelectedRow();if(r<0)return;txtId.setText(v(r,0));txtPetId.setText(v(r,1));txtDate.setText(v(r,3));txtLocation.setText(v(r,4));txtPhone.setText(v(r,5));comboStatus.setSelectedItem(v(r,6));txtDesc.setText(v(r,7));} private String v(int r,int c){Object o=model.getValueAt(r,c);return o==null?"":String.valueOf(o);} private void clear(){txtId.setText("");txtPetId.setText("");txtDate.setText("");txtLocation.setText("");txtPhone.setText("");txtDesc.setText("");table.clearSelection();} private int num(String s,String m){try{return Integer.parseInt(s.trim());}catch(Exception e){throw new AppException(m);}} private void ok(String m){JOptionPane.showMessageDialog(this,m);} private void err(Exception e){JOptionPane.showMessageDialog(this,e.getMessage(),"錯誤",JOptionPane.ERROR_MESSAGE);}
}
