package controller;

import exception.AppException;
import model.ServiceBooking;
import service.ServiceBookingService;
import service.impl.ServiceBookingServiceImpl;
import util.UiStyle;
import util.IconFactory;
import javax.swing.*;import javax.swing.table.DefaultTableModel;import java.awt.*;

public class ServiceBookingFrame extends JFrame {
    private JTextField txtId, txtPetId, txtProvider, txtDate; private JComboBox<String> comboType, comboStatus; private JTextArea txtNote; private JTable table; private DefaultTableModel model; private final ServiceBookingService service=new ServiceBookingServiceImpl();
    public ServiceBookingFrame(){ initialize(); loadData(); }
    private void initialize(){ setTitle("PetLife - 寵物服務預約 CRUD"); setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); setSize(1080,680); setLocationRelativeTo(null); JPanel root=new JPanel(null); root.setBackground(UiStyle.BG); setContentPane(root); JLabel title=UiStyle.title("寵物服務預約"); title.setBounds(32,24,260,38); root.add(title); JButton back=UiStyle.secondaryButton("返回首頁"); back.setIcon(IconFactory.icon(IconFactory.Type.BACK,16,UiStyle.PRIMARY_DARK)); back.setBounds(900,28,120,34); root.add(back); back.addActionListener(e->{new HomeFrame().setVisible(true);dispose();}); JPanel form=new UiStyle.RoundedPanel(28, Color.WHITE); form.setBounds(30,85,360,520); root.add(form); JLabel ft=new JLabel("服務資料"); ft.setFont(UiStyle.font(Font.BOLD,20)); ft.setBounds(24,20,180,30); form.add(ft); txtId=input(form,"ID",70,true); txtPetId=input(form,"寵物ID *",115,false); comboType=combo(form,"服務類型",new String[]{"美容","旅館","保姆","散步","獸醫預約","到府照護"},160); txtProvider=input(form,"店家/人員",205,false); txtDate=input(form,"日期 yyyy-mm-dd",250,false); comboStatus=combo(form,"狀態",new String[]{"待確認","已預約","已完成","已取消"},295); JLabel nl=new JLabel("備註"); nl.setFont(UiStyle.font(Font.PLAIN,14)); nl.setBounds(24,340,90,24); form.add(nl); txtNote=new JTextArea(); txtNote.setLineWrap(true); txtNote.setFont(UiStyle.font(Font.PLAIN,14)); form.add(new JScrollPane(txtNote)); ((JScrollPane)form.getComponent(form.getComponentCount()-1)).setBounds(125,340,197,120); addButtons(root); model=new DefaultTableModel(new Object[]{"ID","寵物ID","寵物名","服務","店家/人員","日期","狀態","備註"},0){public boolean isCellEditable(int r,int c){return false;}}; table=new JTable(model); table.setRowHeight(28); table.setFont(UiStyle.font(Font.PLAIN,13)); table.getTableHeader().setFont(UiStyle.font(Font.BOLD,13)); UiStyle.styleTable(table); JScrollPane sp=new JScrollPane(table); sp.setBounds(415,160,610,445); root.add(sp); table.getSelectionModel().addListSelectionListener(e->{if(!e.getValueIsAdjusting())fill();}); }
    private void addButtons(JPanel root){ JPanel p=new JPanel(null); p.setBackground(UiStyle.BG); p.setBounds(415,85,610,62); root.add(p); String[] n={"新增","修改","刪除","清除","重新整理"}; for(int i=0;i<n.length;i++){ JButton b=i==0?UiStyle.primaryButton(n[i]):UiStyle.secondaryButton(n[i]); if(i==0)b.setIcon(IconFactory.icon(IconFactory.Type.ADD,16,Color.WHITE)); else if(i==1)b.setIcon(IconFactory.icon(IconFactory.Type.EDIT,16,UiStyle.PRIMARY_DARK)); else if(i==2)b.setIcon(IconFactory.icon(IconFactory.Type.DELETE,16,UiStyle.PRIMARY_DARK)); else if(i==4)b.setIcon(IconFactory.icon(IconFactory.Type.REFRESH,16,UiStyle.PRIMARY_DARK)); b.setBounds(i*105,10,i==4?120:90,38); p.add(b); final int k=i; b.addActionListener(e->{if(k==0)add();else if(k==1)update();else if(k==2)delete();else if(k==3)clear();else loadData();});}}
    private JTextField input(JPanel p,String t,int y,boolean ro){ JLabel l=new JLabel(t); l.setFont(UiStyle.font(Font.PLAIN,14)); l.setBounds(24,y,95,28); p.add(l); JTextField f=new JTextField(); f.setFont(UiStyle.font(Font.PLAIN,14)); f.setEditable(!ro); f.setBounds(125,y,197,32); UiStyle.styleField(f); p.add(f); return f;} private JComboBox<String> combo(JPanel p,String t,String[] items,int y){ JLabel l=new JLabel(t); l.setFont(UiStyle.font(Font.PLAIN,14)); l.setBounds(24,y,95,28); p.add(l); JComboBox<String> c=new JComboBox<>(items); c.setFont(UiStyle.font(Font.PLAIN,14)); c.setBounds(125,y,197,30); p.add(c); return c;}
    private ServiceBooking read(boolean needId){ return new ServiceBooking(needId?num(txtId.getText(),"請先選擇資料"):0,num(txtPetId.getText(),"寵物ID請輸入整數"),"",comboType.getSelectedItem().toString(),txtProvider.getText().trim(),txtDate.getText().trim(),comboStatus.getSelectedItem().toString(),txtNote.getText().trim());}
    private void add(){try{service.add(read(false));ok("新增成功");clear();loadData();}catch(Exception e){err(e);}} private void update(){try{service.update(read(true));ok("修改成功");clear();loadData();}catch(Exception e){err(e);}} private void delete(){try{int id=num(txtId.getText(),"請先選擇資料");if(JOptionPane.showConfirmDialog(this,"確定刪除？","確認",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){service.delete(id);clear();loadData();}}catch(Exception e){err(e);}}
    private void loadData(){try{model.setRowCount(0);for(ServiceBooking b:service.getAll())model.addRow(new Object[]{b.getId(),b.getPetId(),b.getPetName(),b.getServiceType(),b.getProviderName(),b.getBookingDate(),b.getStatus(),b.getNote()});}catch(Exception e){err(e);}} private void fill(){int r=table.getSelectedRow();if(r<0)return;txtId.setText(v(r,0));txtPetId.setText(v(r,1));comboType.setSelectedItem(v(r,3));txtProvider.setText(v(r,4));txtDate.setText(v(r,5));comboStatus.setSelectedItem(v(r,6));txtNote.setText(v(r,7));} private String v(int r,int c){Object o=model.getValueAt(r,c);return o==null?"":String.valueOf(o);} private void clear(){txtId.setText("");txtPetId.setText("");txtProvider.setText("");txtDate.setText("");txtNote.setText("");table.clearSelection();} private int num(String s,String m){try{return Integer.parseInt(s.trim());}catch(Exception e){throw new AppException(m);}} private void ok(String m){JOptionPane.showMessageDialog(this,m);} private void err(Exception e){JOptionPane.showMessageDialog(this,e.getMessage(),"錯誤",JOptionPane.ERROR_MESSAGE);}
}
